# This rule is not used by the project zack itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the zack.my.domain.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zack
    app.kubernetes.io/managed-by: kustomize
  name: z21-editor-role
rules:
- apiGroups:
  - zack.my.domain
  resources:
  - z21s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zack.my.domain
  resources:
  - z21s/status
  verbs:
  - get
