# This rule is not used by the project zack itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over zack.my.domain.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zack
    app.kubernetes.io/managed-by: kustomize
  name: z21-admin-role
rules:
- apiGroups:
  - zack.my.domain
  resources:
  - z21s
  verbs:
  - '*'
- apiGroups:
  - zack.my.domain
  resources:
  - z21s/status
  verbs:
  - get
