# This rule is not used by the project zack itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to zack.my.domain resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zack
    app.kubernetes.io/managed-by: kustomize
  name: z21-viewer-role
rules:
- apiGroups:
  - zack.my.domain
  resources:
  - z21s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zack.my.domain
  resources:
  - z21s/status
  verbs:
  - get
