apiVersion: zack.trains.io/v1alpha1
kind: Detector
metadata:
  labels:
    app.kubernetes.io/name: zack
    app.kubernetes.io/managed-by: kustomize
  name: detector-sample
spec:
  # TODO(user): Add fields here
