apiVersion: zack.my.domain/v1alpha1
kind: Z21
metadata:
  labels:
    app.kubernetes.io/name: zack
    app.kubernetes.io/managed-by: kustomize
  name: z21-sample
spec:
  # TODO(user): Add fields here
